#!/bin/bash

# govc-autologin Bash completion script,
# shamelessly modified from the original govc_bash_completion by govmomi.

_govc-autologin_complete()
{
	local cur prev subcmd
	prev=${COMP_WORDS[COMP_CWORD-1]}
	cur=${COMP_WORDS[COMP_CWORD]}
	subcmd=${COMP_WORDS[1]}
	COMPREPLY=()

	if [[ ${prev} == "govc" ]] ; then # show subcommands, no options
		COMPREPLY=( $(compgen -W "$($GOVC_REAL_BIN -h | grep -v Usage | tr -s '\n' ' ')" -- ${cur}) )
		return 0

	elif [[ ${cur} == "-"* ]] ; then
		: # drop out and show options

	elif [[ ${subcmd} == "ls" ]] ; then # not completing an option, try for appropriate values
		if [[ ${prev} == "-t" ]] ; then
			COMPREPLY=( $(compgen -W "$($GOVC_REAL_BIN ls -l "/**" | awk '{print $2}' | \
				sort -u | tr -d '()' | tr '\n' ' '  )" -- ${cur}) )
		else
			COMPREPLY=( $(compgen -W "$($GOVC_REAL_BIN ls "${cur:-/*}*" | tr -s '\n' ' ' )" -- ${cur}) )
		fi

	elif [[ ${subcmd} == "vm."* || ${prev} == "-vm" ]] ; then  
		COMPREPLY=( $(compgen -W "$($GOVC_REAL_BIN ls -t VirtualMachine -l "${cur}*" | \
			awk '{print $1}' | tr -s '\n' ' ' )" -- ${cur}) )
	fi

	# did not hit any specifcs so show all options from help
	if [[ -z ${COMPREPLY} ]]; then
		COMPREPLY=( $(compgen -W "-h $($GOVC_REAL_BIN ${subcmd} -h | awk '{print $1}' | \
		   	grep "^-" | sed -e 's/=.*//g' | tr -s '\n' ' ' )" -- ${cur}) )
	fi

	return 0
}

complete -F _govc-autologin_complete govc
