#!/bin/sh

# Get VM ID by its name with govc,
# assuming each VM has a unique name accross vSphere datacenters.

# Make sure we have logged-in.
if [ -z "$GOVC_LOGGED_IN" ]; then
    export GOVC_VMID_LAST_ARGS="$@"
    govc
fi

VM="$1"
DC=$(govc ls /*/vm/"$VM" | cut -d '/' -f 2)

if [ -n "$@" ]; then
    govc vm.info -json -dc "$DC" "$VM"            |\
        jq '.VirtualMachines[0].Summary.Vm.Value' |\
        tr -d '"'
else
    echo "USAGE: $(basename $0) VM_NAME"
fi
