#!/bin/bash

#####################################################################################
#                                                                                   #
# govc-vmrc                                                                         #
#                                                                                   #
# Open VM console by its name with VMRC,                                            #
# assuming each VM has a unique name accross vSphere datacenters.                   #
#                                                                                   #
# Copyleft 🄯 2022 Ellam ByDefault <ellam.bydefault@gmail.com>. All rights reversed. #
#                                                                                   #
#####################################################################################

print_help() {
    cat <<EOF
Open VM console by its name with VMRC

USAGE: $(basename $0) VM_NAME
EOF
}

VM="$1"

case "$VM" in
    '-h' | '--help' )
        print_help
        ;;
    * )
        if [ ! -z "$VM" ]; then
            if [ ! -z "$GOVC_LOGGED_IN" ]; then
                $REAL_VMRC -U "$GOVC_USERNAME" -P "$GOVC_PASSWORD" -H "$GOVC_URL" -M $(govc-vmid "$VM") &
            else
                # Not yet logged-in
                export GOVC_VMRC_LAST_ARGS="$VM"
                govc
            fi
        else
            print_help
        fi
        ;;
esac
